### ISSUE TITLE
CI failing unexpectedly now

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#73] opened 2017-05-15 21:51 UTC
The CI is breaking because tests from the monadic-eval package are failing.  The failures are coming from the original scribble paper (which hasn't been modified) and which file fails seems to be chosen at random.  

Locally running `raco test --drdr --package monadic-eval` works fine for me with 252/252 tests passing.

Not sure what's going on here.  @philnguyen: any ideas?

**Comment by philnguyen** [comment] 2017-05-15 23:54
I'm suspecting something. Let me give it a try. I'm obtaining the lock of `.travis.yml` for now

**Comment by philnguyen** [comment] 2017-05-16 00:08
The problem is the script by default uses all 32 cores on the Travis CI server and times out at 90s. I needed to fix it by both `--timeout +inf.0` and `-j 2` (otherwise they'll still killed us for using all their cores for too long)

Fixed with commit 29e03ad2661ebf1ea8b3eb171c31808f73d0a90e

**Closed as completed by philnguyen** 2017-05-16 00:09 UTC

**Comment by dvanhorn** [comment] 2017-05-16 02:09
Thanks!
